[package]
name = "china-ip"
version = "0.1.0"
edition = "2021"
description = "a rust library determine a given ip is inside China or not"
license = "GPL-3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
